name: lint

on:
  push:
    tags:
      - v*
    branches: [main]
  pull_request:
    branches: [main]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Lint and Test
        run: make test